# Generated by Django 3.0.8 on 2020-08-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0003_label_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='label',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='color',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
